# Generated by Django 2.2.3 on 2019-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(default=1, upload_to='teenager/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
