# Generated by Django 2.2.3 on 2019-07-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenager', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name_of_school',
        ),
    ]
