# Generated by Django 2.2.3 on 2019-08-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenager', '0004_auto_20190730_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Image',
            new_name='image',
        ),
    ]
