# Generated by Django 2.2.3 on 2020-12-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenager', '0007_student_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_of_birth']},
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='teenager/%Y/%m/%d/'),
        ),
    ]
