# Generated by Django 2.2.3 on 2020-12-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenager', '0008_auto_20201215_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=225),
        ),
    ]
